name: "vot"
platform: "tensorrt_plan"
max_batch_size: 0
input {
  name: "image_tensor:0"
  data_type: TYPE_INT32
  dims: 256
  dims: 256
  dims: 3
  reshape { shape: [1, 256, 256, 3] }
}
output {
  name: "detection_boxes"
  data_type: TYPE_FP32
  dims: [ 100, 4 ]
  reshape: { shape: [1, 100, 4] }
}
output {
  name: "detection_scores"
  data_type: TYPE_FP32
  dims: [ 100 ]
  reshape: { shape: [1, 100] }
}
output {
  name: "detection_classes"
  data_type: TYPE_FP32
  dims: [ 100 ]
  reshape: { shape: [1, 100] }
}
output {
  name: "num_detections"
  data_type: TYPE_FP32
  dims: [ 1 ]
}
default_model_filename: "traffic_model_fp16_xavier_nx.plan"
