package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

filegroup(
    name = "data",
    srcs = glob([
        "*.pbtxt",
        "*.tflite",
        "traffic_frames/*.bmp",
    ]),
)
